### ISSUE TITLE
Registration issue's

### ISSUE THREAD

**Issue by BlissMediaSolutions** [BlissMediaSolutions/Book-Xchange#2]
After successfully registering, the user isn't told this has happened - there's no feedback.
It would probably also be an idea to blank out the text boxes after successful registration, if they stay on the registration page & aren't re-directed elsewhere.

Additionally, if they haven't completed all fields for registration, while the system wont complete the registration, there's no feedback to the user about missing data.

*tested on Firefox 46.0

**Comment by s9998373** [comment]
Good catch. I disabled validation for testing and haven't implemented a callback that the user can see. The backend code is there, it's just a matter of an ng-show element that displays depending on the server's response.
